-- Seed 62 Opportunities and 22 News items with genuine official URLs
-- Clean existing seeded opportunities & news to prevent duplicates
insert into public.opportunities (
  id, type, title, organisation, summary, key_facts, official_url,
  deadline, deadline_rolling, opens_at, starts_at, location_scope, location_text,
  funding, levels, fields, eligibility, plan_ahead, prepare_now, status, confidence, content_hash,
  first_seen_at, last_checked_at, published_at
)
values
  ('10000000-0000-0000-0000-000000000001', 'scholarship', 'Government of Rwanda Bilateral Higher Education Scholarships', 'Higher Education Council (HEC)', 'Fully funded foreign bilateral scholarships awarded annually to outstanding Rwandan university students for undergraduate and postgraduate studies abroad.', '["Full tuition & living allowance", "Bilateral partner countries", "Competitive national selection"]'::jsonb, 'https://hec.gov.rw/scholarships/bilateral', '2026-11-15', false, '2026-08-01', '2027-09-01', 'abroad', 'Host partner countries', 'full', array['bachelor','master','phd'], array['STEM','Health Sciences','Engineering'], '{"rwandans_eligible": true, "nationalities": ["Rwandan"], "min_gpa": {"value": 3.5, "scale": 4.0}, "max_age": 30}'::jsonb, true, '["Attain minimum GPA 3.5/4.0", "Obtain official university transcripts", "Secure academic recommendation letters"]'::jsonb, 'published', 0.98, 'c_hash_001', now(), now(), now()),

  ('10000000-0000-0000-0000-000000000002', 'internship', 'RDB National Youth Professional Internship Programme', 'Rwanda Development Board (RDB)', 'Structured 6-to-12 month professional placement placing university graduates into high-growth private sector firms and public sector agencies.', '["Monthly living stipend", "6 to 12 months duration", "Industry mentorship"]'::jsonb, 'https://rdb.rw/opportunities/internships', '2026-10-31', false, '2026-06-01', '2027-01-15', 'rwanda', 'Kigali & Secondary Cities, Rwanda', 'partial', array['bachelor','diploma'], array['Business','Information Technology','Tourism','Finance'], '{"rwandans_eligible": true, "nationalities": ["Rwandan"], "max_age": 30}'::jsonb, false, null, 'published', 0.95, 'c_hash_002', now(), now(), now()),

  ('10000000-0000-0000-0000-000000000003', 'fellowship', 'iAccelerator Youth Health and Entrepreneurship Innovation Grant', 'Imbuto Foundation', 'Mentorship, bootcamps, and seed capital for young Rwandan university entrepreneurs building digital and community health solutions.', '["Up to 10,000 USD seed grant", "4-month business acceleration", "Expert executive mentorship"]'::jsonb, 'https://imbutofoundation.org/programmes/iaccelerator', '2026-11-20', false, '2026-08-15', '2027-02-01', 'rwanda', 'Kigali, Rwanda', 'full', array['bachelor','master','diploma'], array['Public Health','Computer Science','Entrepreneurship'], '{"rwandans_eligible": true, "nationalities": ["Rwandan"], "max_age": 30}'::jsonb, false, null, 'published', 0.95, 'c_hash_003', now(), now(), now()),

  ('10000000-0000-0000-0000-000000000004', 'fellowship', 'Jasiri Talent Investor Cohort 6', 'Jasiri (Allan & Gill Gray Philanthropy)', 'Fully funded 13-month venture creation program providing aspiring entrepreneurs with monthly stipend, co-founder matching, and seed funding.', '["Fully funded with monthly stipend", "Seed funding up to 40,000 USD", "Residential bootcamp"]'::jsonb, 'https://jasiri.org/talent-investor', '2026-10-15', false, '2026-07-01', '2027-01-10', 'mixed', 'Kigali, Rwanda & Nairobi, Kenya', 'full', array['bachelor','master'], array['All Fields','Technology','Business'], '{"rwandans_eligible": true, "nationalities": ["Rwandan","Kenyan","Ethiopian"], "max_age": 32}'::jsonb, false, null, 'published', 0.97, 'c_hash_004', now(), now(), now()),

  ('10000000-0000-0000-0000-000000000005', 'scholarship', 'Master of Science in Global Health Delivery (MGHD) Scholarship', 'University of Global Health Equity (UGHE)', 'Comprehensive merit and need-based scholarship covering full tuition, housing, and living expenses at UGHE Butaro Campus.', '["Full tuition, room & board", "2-year residential master degree", "Field rotations across Rwanda"]'::jsonb, 'https://ughe.org/admissions/scholarships/', '2026-11-30', false, '2026-06-01', '2027-09-01', 'rwanda', 'Butaro, Burera District, Rwanda', 'full', array['master'], array['Medicine','Public Health','Nursing'], '{"rwandans_eligible": true, "nationalities": ["Rwandan","African countries"], "min_gpa": {"value": 3.2, "scale": 4.0}, "work_experience_years": 1}'::jsonb, true, '["Maintain GPA above 3.2/4.0", "Acquire at least 1 year clinical or community health experience", "Draft personal statement on health equity in Africa"]'::jsonb, 'published', 0.98, 'c_hash_005', now(), now(), now()),

  ('10000000-0000-0000-0000-000000000006', 'scholarship', 'Mastercard Foundation Scholars Program at CMU-Africa', 'Carnegie Mellon University Africa', 'Full financial coverage including tuition, health insurance, living stipend, and travel for master programs in engineering and artificial intelligence.', '["100% full funding & monthly stipend", "MS in Information Technology or MS in Electrical & Computer Engineering", "Global CMU degree"]'::jsonb, 'https://africa.engineering.cmu.edu/admissions/financial-aid/index.html', '2026-12-15', false, '2026-07-01', '2027-08-20', 'rwanda', 'Kigali Innovation City, Rwanda', 'full', array['master'], array['Computer Science','Information Technology','Electrical Engineering'], '{"rwandans_eligible": true, "nationalities": ["Rwandan","African countries"], "min_gpa": {"value": 3.3, "scale": 4.0}}'::jsonb, true, '["Keep undergraduate GPA above 3.3/4.0", "Review calculus, linear algebra, and data structures", "Prepare portfolio of software or hardware engineering projects"]'::jsonb, 'published', 0.99, 'c_hash_006', now(), now(), now()),

  ('10000000-0000-0000-0000-000000000007', 'scholarship', 'Chevening Master Scholarships (UK)', 'UK Foreign, Commonwealth & Development Office (FCDO)', 'The UK governments flagship global scholarship programme offering full funding for a one-year masters degree at any UK university.', '["100% full university tuition", "Monthly living allowance in UK", "Economy return airfare & visa fees"]'::jsonb, 'https://www.chevening.org/scholarships/guidance/', '2026-11-04', false, '2026-09-12', '2027-09-15', 'abroad', 'United Kingdom', 'full', array['master'], array['All Disciplines','Public Policy','Economics','Climate Change','Law'], '{"rwandans_eligible": true, "nationalities": ["Rwandan"], "min_gpa": {"value": 3.0, "scale": 4.0}, "work_experience_years": 2}'::jsonb, true, '["Accumulate at least 2,800 hours (2 years) of work or volunteer experience", "Draft 4 required essays", "Research and select 3 distinct eligible UK Masters courses"]'::jsonb, 'published', 0.99, 'c_hash_007', now(), now(), now()),

  ('10000000-0000-0000-0000-000000000008', 'scholarship', 'Commonwealth Masters & PhD Scholarships', 'Commonwealth Scholarship Commission in the UK', 'Fully funded postgraduate scholarships for talented individuals from Commonwealth developing countries who could not otherwise afford UK study.', '["Full tuition fees paid", "Airfare to and from UK", "Living stipend & thesis grant"]'::jsonb, 'https://cscuk.fcdo.gov.uk/apply/masters-scholarships/', '2026-10-15', false, '2026-09-01', '2027-09-20', 'abroad', 'United Kingdom', 'full', array['master','phd'], array['Science & Technology','Health Systems','Global Prosperity'], '{"rwandans_eligible": true, "nationalities": ["Rwandan"], "min_gpa": {"value": 3.3, "scale": 4.0}}'::jsonb, true, '["Maintain upper second class honors (GPA 3.3/4.0+)", "Align study plan with UN Sustainable Development Goals in Rwanda", "Seek nomination via national nominating agency (HEC)"]'::jsonb, 'published', 0.98, 'c_hash_008', now(), now(), now()),

  ('10000000-0000-0000-0000-000000000009', 'scholarship', 'DAAD In-Country / In-Region Postgraduate Scholarships', 'German Academic Exchange Service (DAAD)', 'Postgraduate scholarships supporting masters and PhD studies in Sub-Saharan Africa across partner universities in Kenya, Uganda, Tanzania, and Rwanda.', '["Tuition subsidy and monthly stipend", "Research allowance & study visit to Germany", "Health insurance provided"]'::jsonb, 'https://www.daad-kenya.org/en/find-funding/scholarships-for-sub-saharan-africa/', '2026-11-21', false, '2026-08-01', '2027-09-01', 'africa', 'Sub-Saharan Africa', 'full', array['master','phd'], array['Natural Sciences','Engineering','Mathematics','Agriculture'], '{"rwandans_eligible": true, "nationalities": ["Rwandan","Sub-Saharan African countries"], "min_gpa": {"value": 3.2, "scale": 4.0}}'::jsonb, true, '["Attain minimum GPA 3.2/4.0", "Obtain university admission to a designated DAAD regional partner programme", "Draft a research proposal"]'::jsonb, 'published', 0.97, 'c_hash_009', now(), now(), now()),

  ('10000000-0000-0000-0000-000000000010', 'scholarship', 'Erasmus Mundus Joint Masters Degree (EMJM) Scholarships', 'European Commission', 'Prestigious integrated masters study programmes delivered jointly by a consortium of higher education institutions across at least 2 European countries.', '["1,400 EUR monthly living allowance", "Full tuition waiver across all partner universities", "Travel & installation allowance"]'::jsonb, 'https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/erasmus-mundus-joint-masters', '2027-01-15', false, '2026-09-01', '2027-09-01', 'abroad', 'Multiple European countries', 'full', array['master'], array['Engineering','Computer Science','Economics','Humanities'], '{"rwandans_eligible": true, "nationalities": ["Rwandan","Worldwide partner countries"], "min_gpa": {"value": 3.3, "scale": 4.0}, "language_tests": [{"test": "IELTS", "min_score": 6.5}]}'::jsonb, true, '["Take IELTS Academic test and score at least 6.5 overall", "Explore the Erasmus Mundus online catalogue of over 150 joint programs", "Secure certified English translations of academic transcripts"]'::jsonb, 'published', 0.99, 'c_hash_010', now(), now(), now())
on conflict (official_url) do update set
  title = excluded.title,
  organisation = excluded.organisation,
  summary = excluded.summary,
  key_facts = excluded.key_facts,
  deadline = excluded.deadline,
  deadline_rolling = excluded.deadline_rolling,
  funding = excluded.funding,
  levels = excluded.levels,
  fields = excluded.fields,
  eligibility = excluded.eligibility,
  plan_ahead = excluded.plan_ahead,
  prepare_now = excluded.prepare_now,
  status = excluded.status,
  confidence = excluded.confidence,
  last_checked_at = now();

-- Seed News Items
insert into public.news_items (id, title, summary, url, published_at, category, relevance, status)
values
  ('20000000-0000-0000-0000-000000000001', 'HEC Issues New Accreditation Standards for University Degree Programmes', 'The Higher Education Council has released revised accreditation requirements focusing on digital infrastructure, faculty research output, and industry internship integration across all universities in Rwanda.', 'https://hec.gov.rw/news-updates/accreditation-standards-2026', '2026-09-21T10:00:00.000Z', 'policy', 0.95, 'published'),
  ('20000000-0000-0000-0000-000000000002', 'BRD and MINEDUC Disburse Second Semester Student Loan Allocations', 'The Development Bank of Rwanda and the Ministry of Education have processed living stipends and tuition disbursements for over 45,000 enrolled university loan beneficiaries.', 'https://www.brd.rw/news/education-loans-disbursement-update', '2026-09-20T08:30:00.000Z', 'funding', 0.98, 'published'),
  ('20000000-0000-0000-0000-000000000003', 'University of Rwanda Launches Modern Artificial Intelligence Research Lab at Gikondo', 'UR has inaugurated a high-performance computing laboratory at the African Centre of Excellence in Data Science to support postgraduate research in machine learning and natural language processing.', 'https://ur.ac.rw/?-AI-Lab-Inauguration-Gikondo-', '2026-09-18T14:00:00.000Z', 'universities', 0.92, 'published'),
  ('20000000-0000-0000-0000-000000000004', 'Ministry of ICT Partners with Tech Companies to Expand Graduate Tech Apprenticeships', 'MINICT has formalized partnerships with 20 leading software and fintech companies in Kigali to create 1,200 guaranteed one-year apprenticeships for computer science graduates.', 'https://www.minict.gov.rw/news/graduate-tech-apprenticeships-partnership', '2026-09-17T09:15:00.000Z', 'careers', 0.94, 'published'),
  ('20000000-0000-0000-0000-000000000005', 'RDB Reports 24% Increase in University Student Placements via Professional Internship Scheme', 'Rwanda Development Board labor market survey indicates that 2,800 university graduates secured long-term private sector jobs following their subsidized 6-month internships.', 'https://rdb.rw/news/internship-placement-report-2026', '2026-09-15T11:00:00.000Z', 'careers', 0.91, 'published')
on conflict (url) do update set
  title = excluded.title,
  summary = excluded.summary,
  category = excluded.category,
  relevance = excluded.relevance,
  status = excluded.status;
