-- Seed sources: 46 opportunity sources (including official bodies, universities, international scholarships, aggregators) + 9 news sources
insert into public.sources (id, name, url, kind, category, is_official, is_aggregator, active, crawl_hint)
values
  -- Government & National Bodies
  ('a0000000-0000-0000-0000-000000000001', 'Higher Education Council (HEC)', 'https://hec.gov.rw', 'html', 'opportunity', true, false, true, '{"listing_url": "https://hec.gov.rw/scholarships", "item_selector": "a.scholarship-item, .view-content a, .news-list a", "url_pattern": "scholarship|call|announcement"}'),
  ('a0000000-0000-0000-0000-000000000002', 'Ministry of Education (MINEDUC)', 'https://www.mineduc.gov.rw', 'html', 'opportunity', true, false, true, '{"listing_url": "https://www.mineduc.gov.rw/updates/announcements", "item_selector": "a[href*=''announcement''], .announcement-list a", "url_pattern": "scholarship|bursary|announcement|opportunity"}'),
  ('a0000000-0000-0000-0000-000000000003', 'Rwanda Development Board (RDB)', 'https://rdb.rw', 'html', 'opportunity', true, false, true, '{"listing_url": "https://rdb.rw/opportunities/", "item_selector": "a[href*=''internship''], a[href*=''career''], .opportunities-card a", "url_pattern": "internship|trainee|capacity-building"}'),
  ('a0000000-0000-0000-0000-000000000004', 'Development Bank of Rwanda (BRD)', 'https://www.brd.rw', 'html', 'opportunity', true, false, true, '{"listing_url": "https://www.brd.rw/education-financing/", "item_selector": "a[href*=''loan''], a[href*=''education''], a[href*=''bursary'']", "url_pattern": "scheme|student-financing|call"}'),
  ('a0000000-0000-0000-0000-000000000005', 'Rwanda Biomedical Centre (RBC)', 'https://rbc.gov.rw', 'html', 'opportunity', true, false, true, '{"listing_url": "https://rbc.gov.rw/index.php?id=707", "item_selector": "a[href*=''internship''], a[href*=''fellowship''], a[href*=''training'']", "url_pattern": "training|fellowship|symposium|internship"}'),
  ('a0000000-0000-0000-0000-000000000006', 'Ministry of ICT and Innovation (MINICT)', 'https://www.minict.gov.rw', 'html', 'opportunity', true, false, true, '{"listing_url": "https://www.minict.gov.rw/updates/announcements", "item_selector": "a[href*=''announcement''], a[href*=''initiative''], a[href*=''challenge'']", "url_pattern": "challenge|training|innovation|bootcamp"}'),
  ('a0000000-0000-0000-0000-000000000007', 'National Council of Nurses and Midwives (NCNM)', 'https://ncnm.rw', 'html', 'opportunity', true, false, true, '{"listing_url": "https://ncnm.rw/announcements", "item_selector": "a[href*=''cpd''], a[href*=''training''], a[href*=''event'']", "url_pattern": "cpd|training|symposium|scholarship"}'),

  -- Foundations, Hubs, Employers
  ('a0000000-0000-0000-0000-000000000008', 'Imbuto Foundation', 'https://imbutofoundation.org', 'html', 'opportunity', true, false, true, '{"listing_url": "https://imbutofoundation.org/programmes", "item_selector": "a[href*=''iaccelerator''], a[href*=''scholarship''], a[href*=''call'']", "url_pattern": "programme|call|application"}'),
  ('a0000000-0000-0000-0000-000000000009', 'Mastercard Foundation (Scholars Program)', 'https://mastercardfdn.org', 'html', 'opportunity', true, false, true, '{"listing_url": "https://mastercardfdn.org/all/scholars/becoming-a-scholar/apply-to-the-scholars-program/", "item_selector": "a[href*=''scholars''], a[href*=''apply''], .partner-card a", "url_pattern": "apply|scholars-program|partner"}'),
  ('a0000000-0000-0000-0000-000000000010', 'kLab Rwanda', 'https://klab.rw', 'html', 'opportunity', true, false, true, '{"listing_url": "https://klab.rw/academy", "item_selector": "a[href*=''bootcamp''], a[href*=''program''], a[href*=''apply'']", "url_pattern": "bootcamp|cohort|academy"}'),
  ('a0000000-0000-0000-0000-000000000011', 'Norrsken East Africa', 'https://www.norrsken.org/eastafrica', 'html', 'opportunity', true, false, true, '{"listing_url": "https://www.norrsken.org/eastafrica/programs", "item_selector": "a[href*=''fellowship''], a[href*=''incubator''], a[href*=''accelerator'']", "url_pattern": "program|fellowship|apply"}'),
  ('a0000000-0000-0000-0000-000000000012', 'Kigali International Financial Centre (KIFC)', 'https://kifc.com', 'html', 'opportunity', true, false, true, '{"listing_url": "https://kifc.com/academy/", "item_selector": "a[href*=''training''], a[href*=''fellowship''], a[href*=''talent'']", "url_pattern": "training|talent|internship"}'),
  ('a0000000-0000-0000-0000-000000000013', 'ALX Africa', 'https://www.alxafrica.com', 'html', 'opportunity', true, false, true, '{"listing_url": "https://www.alxafrica.com/programmes/", "item_selector": "a[href*=''/programmes/''], .program-card a", "url_pattern": "programme|tech-skills|pathway"}'),
  ('a0000000-0000-0000-0000-000000000014', 'Rwanda ICT Chamber', 'https://ictchamber.rw', 'html', 'opportunity', true, false, true, '{"listing_url": "https://ictchamber.rw/initiatives/", "item_selector": "a[href*=''internship''], a[href*=''program''], a[href*=''challenge'']", "url_pattern": "challenge|internship|skills"}'),
  ('a0000000-0000-0000-0000-000000000015', 'Jasiri Talent Investor', 'https://jasiri.org', 'html', 'opportunity', true, false, true, '{"listing_url": "https://jasiri.org/talent-investor/", "item_selector": "a[href*=''apply''], a[href*=''fellowship''], a[href*=''cohort'']", "url_pattern": "apply|cohort|fellowship"}'),

  -- Rwandan Universities
  ('a0000000-0000-0000-0000-000000000016', 'University of Rwanda (UR)', 'https://ur.ac.rw', 'html', 'opportunity', true, false, true, '{"listing_url": "https://ur.ac.rw/?-Calls-and-Opportunities-", "item_selector": "a[href*=''rubrique''], a[href*=''call''], a[href*=''scholarship'']", "url_pattern": "scholarship|call|fellowship|announcement"}'),
  ('a0000000-0000-0000-0000-000000000017', 'University of Global Health Equity (UGHE)', 'https://ughe.org', 'html', 'opportunity', true, false, true, '{"listing_url": "https://ughe.org/admissions/scholarships/", "item_selector": "a[href*=''scholarship''], a[href*=''fellowship'']", "url_pattern": "scholarship|financial-aid|fellowship"}'),
  ('a0000000-0000-0000-0000-000000000018', 'Carnegie Mellon University Africa', 'https://africa.engineering.cmu.edu', 'html', 'opportunity', true, false, true, '{"listing_url": "https://africa.engineering.cmu.edu/admissions/financial-aid/index.html", "item_selector": "a[href*=''financial-aid''], a[href*=''scholarship'']", "url_pattern": "scholarship|financial-aid|fellowship"}'),
  ('a0000000-0000-0000-0000-000000000019', 'African Leadership University (ALU Rwanda)', 'https://www.alueducation.com', 'html', 'opportunity', true, false, true, '{"listing_url": "https://www.alueducation.com/financial-aid/", "item_selector": "a[href*=''scholarship''], a[href*=''financial-aid''], a[href*=''fellowship'']", "url_pattern": "scholarship|fellowship|grant"}'),
  ('a0000000-0000-0000-0000-000000000020', 'Kepler College', 'https://kepler.org', 'html', 'opportunity', true, false, true, '{"listing_url": "https://kepler.org/admissions/scholarships/", "item_selector": "a[href*=''scholarship''], a[href*=''apply'']", "url_pattern": "scholarship|opportunity"}'),
  ('a0000000-0000-0000-0000-000000000021', 'Adventist University of Central Africa (AUCA)', 'https://auca.ac.rw', 'html', 'opportunity', true, false, true, '{"listing_url": "https://auca.ac.rw/announcements/", "item_selector": "a[href*=''scholarship''], a[href*=''announcement'']", "url_pattern": "scholarship|announcement|call"}'),
  ('a0000000-0000-0000-0000-000000000022', 'Mount Kigali University', 'https://mountkigaliuniversity.ac.rw', 'html', 'opportunity', true, false, true, '{"listing_url": "https://mountkigaliuniversity.ac.rw/scholarships/", "item_selector": "a[href*=''scholarship''], a[href*=''opportunity'']", "url_pattern": "scholarship|grant"}'),
  ('a0000000-0000-0000-0000-000000000023', 'INES-Ruhengeri', 'https://ines.ac.rw', 'html', 'opportunity', true, false, true, '{"listing_url": "https://ines.ac.rw/opportunities/", "item_selector": "a[href*=''call''], a[href*=''scholarship''], a[href*=''job'']", "url_pattern": "call|scholarship|internship"}'),
  ('a0000000-0000-0000-0000-000000000024', 'University of Kigali (UoK)', 'https://uok.ac.rw', 'html', 'opportunity', true, false, true, '{"listing_url": "https://uok.ac.rw/scholarships/", "item_selector": "a[href*=''scholarship''], a[href*=''call'']", "url_pattern": "scholarship|call"}'),

  -- International Scholarships & Fellowships (Official)
  ('a0000000-0000-0000-0000-000000000025', 'Chevening Scholarships', 'https://www.chevening.org', 'html', 'opportunity', true, false, true, '{"listing_url": "https://www.chevening.org/scholarships/guidance/", "item_selector": "a[href*=''rwanda''], a[href*=''scholarships''], a[href*=''guidance'']", "url_pattern": "scholarship|apply|rwanda"}'),
  ('a0000000-0000-0000-0000-000000000026', 'Commonwealth Scholarships', 'https://cscuk.fcdo.gov.uk', 'html', 'opportunity', true, false, true, '{"listing_url": "https://cscuk.fcdo.gov.uk/apply/", "item_selector": "a[href*=''masters-scholarships''], a[href*=''phd-scholarships''], a[href*=''fellowships'']", "url_pattern": "masters|phd|fellowship|apply"}'),
  ('a0000000-0000-0000-0000-000000000027', 'DAAD German Academic Exchange', 'https://www.daad.de', 'html', 'opportunity', true, false, true, '{"listing_url": "https://www.daad-kenya.org/en/find-funding/scholarships-for-sub-saharan-africa/", "item_selector": "a[href*=''scholarship''], a[href*=''programme'']", "url_pattern": "programme|scholarship|call"}'),
  ('a0000000-0000-0000-0000-000000000028', 'Erasmus Mundus Joint Masters', 'https://erasmus-plus.ec.europa.eu', 'html', 'opportunity', true, false, true, '{"listing_url": "https://erasmus-plus.ec.europa.eu/opportunities/opportunities-for-individuals/students/erasmus-mundus-joint-masters", "item_selector": "a[href*=''catalogue''], a[href*=''emjm''], a[href*=''master'']", "url_pattern": "joint-master|catalogue|scholarship"}'),
  ('a0000000-0000-0000-0000-000000000029', 'Fulbright Foreign Student Program (U.S. Embassy Rwanda)', 'https://rw.usembassy.gov', 'html', 'opportunity', true, false, true, '{"listing_url": "https://rw.usembassy.gov/education-culture/educational-exchange/", "item_selector": "a[href*=''fulbright''], a[href*=''exchange'']", "url_pattern": "fulbright|exchange|humphrey"}'),
  ('a0000000-0000-0000-0000-000000000030', 'Mandela Washington Fellowship (YALI)', 'https://mandelawashingtonfellowship.org', 'html', 'opportunity', true, false, true, '{"listing_url": "https://mandelawashingtonfellowship.org/apply/", "item_selector": "a[href*=''apply''], a[href*=''fellowship'']", "url_pattern": "apply|fellowship|eligibility"}'),
  ('a0000000-0000-0000-0000-000000000031', 'MEXT Scholarships Japan', 'https://www.studyinjapan.go.jp', 'html', 'opportunity', true, false, true, '{"listing_url": "https://www.rw.emb-japan.go.jp/itpr_en/culture.html", "item_selector": "a[href*=''mext''], a[href*=''scholarship'']", "url_pattern": "mext|scholarship|embassy"}'),
  ('a0000000-0000-0000-0000-000000000032', 'Chinese Government Scholarship (CSC)', 'https://www.campuschina.org', 'html', 'opportunity', true, false, true, '{"listing_url": "https://www.campuschina.org/scholarships/index.html", "item_selector": "a[href*=''program''], a[href*=''scholarship'']", "url_pattern": "scholarship|program|apply"}'),
  ('a0000000-0000-0000-0000-000000000033', 'Stipendium Hungaricum', 'https://stipendiumhungaricum.hu', 'html', 'opportunity', true, false, true, '{"listing_url": "https://stipendiumhungaricum.hu/apply/", "item_selector": "a[href*=''call-for-applications''], a[href*=''apply'']", "url_pattern": "call-for-applications|apply|guidelines"}'),
  ('a0000000-0000-0000-0000-000000000034', 'Swedish Institute Scholarships', 'https://si.se', 'html', 'opportunity', true, false, true, '{"listing_url": "https://si.se/en/apply/scholarships/", "item_selector": "a[href*=''pioneering-women''], a[href*=''scholarship''], a[href*=''global-professionals'']", "url_pattern": "scholarship|apply|call"}'),
  ('a0000000-0000-0000-0000-000000000035', 'Rhodes Scholarship (East Africa)', 'https://www.rhodeshouse.ox.ac.uk', 'html', 'opportunity', true, false, true, '{"listing_url": "https://www.rhodeshouse.ox.ac.uk/scholarships/applications/east-africa/", "item_selector": "a[href*=''east-africa''], a[href*=''apply'']", "url_pattern": "east-africa|how-to-apply"}'),
  ('a0000000-0000-0000-0000-000000000036', 'Gates Cambridge Scholarship', 'https://www.gatescambridge.org', 'html', 'opportunity', true, false, true, '{"listing_url": "https://www.gatescambridge.org/programme/the-scholarship/", "item_selector": "a[href*=''apply''], a[href*=''scholarship'']", "url_pattern": "apply|scholarship|criteria"}'),
  ('a0000000-0000-0000-0000-000000000037', 'Mandela Rhodes Foundation', 'https://www.mandelarhodes.org', 'html', 'opportunity', true, false, true, '{"listing_url": "https://www.mandelarhodes.org/scholarship/apply/", "item_selector": "a[href*=''apply''], a[href*=''scholarship'']", "url_pattern": "apply|scholarship|selection"}'),
  ('a0000000-0000-0000-0000-000000000038', 'Türkiye Scholarships', 'https://turkiyeburslari.gov.tr', 'html', 'opportunity', true, false, true, '{"listing_url": "https://turkiyeburslari.gov.tr/en/announcements", "item_selector": "a[href*=''announcement''], a[href*=''application'']", "url_pattern": "application|announcement|scholarship"}'),
  ('a0000000-0000-0000-0000-000000000039', 'Global Health Corps Fellowship', 'https://ghcorps.org', 'html', 'opportunity', true, false, true, '{"listing_url": "https://ghcorps.org/fellowship/", "item_selector": "a[href*=''apply''], a[href*=''fellowship'']", "url_pattern": "fellowship|apply|roles"}'),
  ('a0000000-0000-0000-0000-000000000040', 'Tony Elumelu Foundation Entrepreneurship', 'https://www.tonyelumelufoundation.org', 'html', 'opportunity', true, false, true, '{"listing_url": "https://www.tonyelumelufoundation.org/programmes", "item_selector": "a[href*=''programme''], a[href*=''apply'']", "url_pattern": "programme|apply|tef-connect"}'),
  ('a0000000-0000-0000-0000-000000000041', 'Google Student Programs & Fellowships', 'https://buildyourfuture.withgoogle.com', 'html', 'opportunity', true, false, true, '{"listing_url": "https://buildyourfuture.withgoogle.com/scholarships", "item_selector": "a[href*=''scholarships/'']", "url_pattern": "scholarships|generation-google|fellowship"}'),
  ('a0000000-0000-0000-0000-000000000042', 'Ashinaga Africa Initiative', 'https://en.ashinaga.org', 'html', 'opportunity', true, false, true, '{"listing_url": "https://en.ashinaga.org/apply/aai/", "item_selector": "a[href*=''apply''], a[href*=''aai'']", "url_pattern": "apply|aai|scholarship"}'),

  -- Aggregators (Discovery Only)
  ('a0000000-0000-0000-0000-000000000043', 'Opportunity Desk', 'https://opportunitydesk.org', 'rss', 'opportunity', false, true, true, '{"feed_url": "https://opportunitydesk.org/feed/", "url_pattern": "scholarship|fellowship|internship|contest"}'),
  ('a0000000-0000-0000-0000-000000000044', 'Opportunities for Africans', 'https://www.opportunitiesforafricans.com', 'rss', 'opportunity', false, true, true, '{"feed_url": "https://www.opportunitiesforafricans.com/feed/", "url_pattern": "scholarship|fellowship|internship|grant"}'),
  ('a0000000-0000-0000-0000-000000000045', 'After School Africa', 'https://www.afterschoolafrica.com', 'rss', 'opportunity', false, true, true, '{"feed_url": "https://www.afterschoolafrica.com/feed/", "url_pattern": "scholarship|fellowship|masters"}'),
  ('a0000000-0000-0000-0000-000000000046', 'Youth Opportunities', 'https://www.youthop.com', 'rss', 'opportunity', false, true, true, '{"feed_url": "https://www.youthop.com/feed", "url_pattern": "scholarships|fellowships|competitions"}'),

  -- News Sources
  ('b0000000-0000-0000-0000-000000000001', 'The New Times (Education)', 'https://www.newtimes.co.rw', 'rss', 'news', true, false, true, '{"feed_url": "https://www.newtimes.co.rw/rss", "url_pattern": "education|university|students|hec|mineduc|scholarship|jobs"}'),
  ('b0000000-0000-0000-0000-000000000002', 'KT Press Rwanda', 'https://www.ktpress.rw', 'rss', 'news', true, false, true, '{"feed_url": "https://www.ktpress.rw/feed/", "url_pattern": "education|university|students|policy|scholarship"}'),
  ('b0000000-0000-0000-0000-000000000003', 'IGIHE (English Edition)', 'https://en.igihe.com', 'rss', 'news', true, false, true, '{"feed_url": "https://en.igihe.com/spip.php?page=backend", "url_pattern": "education|university|students|youth"}'),
  ('b0000000-0000-0000-0000-000000000004', 'Rwanda Broadcasting Agency (RBA)', 'https://www.rba.co.rw', 'html', 'news', true, false, true, '{"listing_url": "https://www.rba.co.rw/education", "item_selector": "a.news-title, .news-item a", "url_pattern": "education|university|students"}'),
  ('b0000000-0000-0000-0000-000000000005', 'University World News (Africa)', 'https://www.universityworldnews.com', 'rss', 'news', true, false, true, '{"feed_url": "https://www.universityworldnews.com/rss/africa.xml", "url_pattern": "rwanda|east-africa|higher-education|students"}'),
  ('b0000000-0000-0000-0000-000000000006', 'HEC Rwanda Announcements', 'https://hec.gov.rw', 'html', 'news', true, false, true, '{"listing_url": "https://hec.gov.rw/news-updates", "item_selector": "a[href*=''news''], a[href*=''announcement'']", "url_pattern": "news|announcement|update"}'),
  ('b0000000-0000-0000-0000-000000000007', 'MINEDUC News', 'https://www.mineduc.gov.rw', 'html', 'news', true, false, true, '{"listing_url": "https://www.mineduc.gov.rw/updates/news", "item_selector": "a[href*=''news''], .news-card a", "url_pattern": "news|press-release|update"}'),
  ('b0000000-0000-0000-0000-000000000008', 'University of Rwanda News', 'https://ur.ac.rw', 'html', 'news', true, false, true, '{"listing_url": "https://ur.ac.rw/?-News-", "item_selector": "a[href*=''article''], a[href*=''rubrique'']", "url_pattern": "article|news"}'),
  ('b0000000-0000-0000-0000-000000000009', 'Ministry of ICT & Innovation News', 'https://www.minict.gov.rw', 'html', 'news', true, false, true, '{"listing_url": "https://www.minict.gov.rw/news", "item_selector": "a[href*=''news''], .news-item a", "url_pattern": "news|press|update"}')
on conflict (id) do update set
  name = excluded.name,
  url = excluded.url,
  kind = excluded.kind,
  category = excluded.category,
  is_official = excluded.is_official,
  is_aggregator = excluded.is_aggregator,
  active = excluded.active,
  crawl_hint = excluded.crawl_hint;
